root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/server-dev-bin cmd/server/main.go"

bin = "tmp/server-dev-bin"

exclude_dir = ["bin", "tmp", "assets"]

exclude_regex = ["_test\\.go"]

exclude_unchanged = true

include_ext = ["go", "html"]

log = "build-errors.log"

stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = true

main_only = false

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = false
