version: "3.9"

services:
  pgsql:
    image: bitnami/postgresql:16.2.0
    ports:
      - 5432:5432
    env_file:
      - ../../.env
    environment:
      - POSTGRESQL_USERNAME=${DATABASE_USER}
      - POSTGRESQL_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRESQL_DATABASE=${DATABASE_NAME}
