// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package serviceRegistry

import (
	"context"
	"github.com/go-chi/chi/v5"
	"github.com/richhh7g/mm-api-nfe/internal/api/controller"
	"github.com/richhh7g/mm-api-nfe/internal/api/route"
	"github.com/richhh7g/mm-api-nfe/internal/infra/data/client/database/sqlc_pg"
	"github.com/richhh7g/mm-api-nfe/internal/infra/data/invoice"
	invoice2 "github.com/richhh7g/mm-api-nfe/internal/usecase/invoice"
)

// Injectors from injector.go:

func NewInvoiceRoute(ctx *context.Context, router *chi.Mux, db sqlc_pg.DBTX) *route.InvoiceRouteImpl {
	invoiceDataSourceImpl := invoice.NewInvoice(ctx, db)
	checkKeyExistsUseCaseImpl := invoice2.NewCheckKeyExistsUseCase(ctx, invoiceDataSourceImpl)
	createInvoiceUseCaseImpl := invoice2.NewCreateInvoiceUseCase(ctx, invoiceDataSourceImpl)
	getInvoiceByKeyUseCaseImpl := invoice2.NewGetInvoiceByKeyUseCase(ctx, invoiceDataSourceImpl)
	invoiceParams := &controller.InvoiceParams{
		Ctx:                    ctx,
		CheckKeyExistsUseCase:  checkKeyExistsUseCaseImpl,
		CreateInvoiceUseCase:   createInvoiceUseCaseImpl,
		GetInvoiceByKeyUseCase: getInvoiceByKeyUseCaseImpl,
	}
	invoiceImpl := controller.NewInvoice(invoiceParams)
	invoiceRouteImpl := route.NewInvoiceRoute(router, invoiceImpl)
	return invoiceRouteImpl
}
