// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc_pg

import (
	"time"
)

type NotasFiscais struct {
	ID         string
	CreatedAt  time.Time
	EmissaoEm  time.Time
	RecebidoEm time.Time
	Cnpj       string
	Chave      string
}
