basePath: /
info:
  contact:
    email: richhh7g@protonmail.com
    name: Richhh7g
    url: https://github.com/richhh7g
  license:
    name: MIT
    url: https://github.com/richhh7g/backend-nota-fiscal/blob/main/LICENSE
  title: NFE API
  version: 1.0.0
paths: {}
swagger: "2.0"
